name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Issue Labeler
      uses: Naturalclar/issue-action@v1.0.0
      with:
        # labels to be set when keyword is found
        labels: triage
        keywords: '['help']'
        
